name: HCL DevOps Test Hub

on: workflow_dispatch

jobs:
    TestHub-Action:
        runs-on: self-hosted
        name: HCL DevOps Test Hub
        steps:
         - name: Execute Test
           uses: HCL-TECH-SOFTWARE/devops-test-hub-action@main
           with:
            serverUrl: https://10.190.97.68.nip.io/test/
            offlineToken: eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJjYjdmOGNiYS0xYmI0LTRiYzItYmEzNi1hNmZlZTQ2YTA4NGQifQ.eyJpYXQiOjE3ODAzMTYzNTUsImp0aSI6ImQyYTM3Mzg3LWNiMjgtYjg0ZC0yMTM1LTU4MmE0YmJhNzZmYiIsImlzcyI6Imh0dHBzOi8vMTAuMTkwLjk3LjY4Lm5pcC5pby9hdXRoL3JlYWxtcy9wbGF0Zm9ybSIsImF1ZCI6Imh0dHBzOi8vMTAuMTkwLjk3LjY4Lm5pcC5pby9hdXRoL3JlYWxtcy9wbGF0Zm9ybSIsInN1YiI6IjU0ZjBiYmQzLThlMjMtNDE5Mi04YjZiLTlmZmI5MWY2MzFmNSIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJ0ZXN0c2VydmVyIiwic2lkIjoidUVjOHltODhyVEFJVkJaZk85VEFMS19OIiwic2NvcGUiOiJlbWFpbCBhY3Igcm9sZXMgYmFzaWMgc2VydmljZV9hY2NvdW50IHByb2ZpbGUgb2ZmbGluZV9hY2Nlc3Mgd2ViLW9yaWdpbnMiLCJhdWRfeCI6ImFjY291bnQifQ.PK63RaZqfmbL15RnkQ3HPvZV_L7FBsO1Q4LYy8SqatAagZyhzIGZ9N3vHiSLQPrl9scGM5Hglw29slQT9Wt4ew
            teamspace: Initial Team Space
            project: Anshul_SVT
            branch: AnsFT
            assetId: 2ff1840b54f05ddcc279c03ffaabb8199d50613c950191f0cfa700baf57319cf
