name: HCL OneTest Server

on: workflow_dispatch

jobs:
    OTS-Action:
        runs-on: self-hosted
        name: HCL OneTest Server
        steps:
         - name: Execute Test
           uses: HCL-TECH-SOFTWARE/onetest-server-action@main
           with:
            serverUrl: https://10.134.59.190.nip.io/
            offlineToken: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIwYWY4NGQzOC0wMzYwLTQwZDQtODBiNy1mMzI4ZWVlZTAyNzYifQ.eyJpYXQiOjE2NjYwMTgzMDYsImp0aSI6ImE3NDRjMzAyLTViNzItNDk5MS1hZGU1LTNhMDFiZWMzNjQyOSIsImlzcyI6Imh0dHBzOi8vMTAuMTM0LjU5LjE5MC5uaXAuaW8vYXV0aC9yZWFsbXMvdGVzdHNlcnZlciIsImF1ZCI6Imh0dHBzOi8vMTAuMTM0LjU5LjE5MC5uaXAuaW8vYXV0aC9yZWFsbXMvdGVzdHNlcnZlciIsInN1YiI6IjljYjM0MjIxLTBlOWMtNDJkMC05MTg4LTZjY2Q5MjIyZDEyZiIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJ0ZXN0c2VydmVyIiwic2Vzc2lvbl9zdGF0ZSI6ImU1Mzk4MjFiLTI1YjQtNGNhNS04NGE0LWE1YmQ2ZWE0YmQwYiIsInNjb3BlIjoidGVzdHNlcnZlciBlbWFpbCBvZmZsaW5lX2FjY2VzcyBwcm9maWxlIiwic2lkIjoiZTUzOTgyMWItMjViNC00Y2E1LTg0YTQtYTViZDZlYTRiZDBiIn0.n7kYdNNC9yAj8kqPtP2y3TQvOBhz0srBeqyTq3XF3cQ
            teamspace: Initial Team Space
            project: Anshul_SVT
            branch: Anshul_Test
            assetId: d6b7f7b9-927e-4157-b7f7-b9927ee15752
