name: HCL DevOps Test UI

on: workflow_dispatch

jobs:
    UI-Action:
        runs-on: self-hosted
        name: HCL DevOps Test UI
        steps:
         - name: Execute Test
           uses: HCL-TECH-SOFTWARE/devops-test-ui-action@main
           with:
            projectDirectory: C:\Users\anshul.kulkarni\HCL\devopstest\workspace\FunctionalTesterDemo
            scriptName: ClassicsJavaA
