name: Rational Test Automation Server

on: workflow_dispatch

jobs:
    OTS-Action:
        runs-on: self-hosted
        name: Rational Test Automation Server
        steps:
         - name: Execute Test
           uses: IBM/devopsauto-testserver-actions@main
           with:
            serverUrl: https://10.134.59.236.nip.io/#/Initial/space
            offlineToken: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIzNTg2MTQwOC1kMjJmLTQ0MjUtODdiOC0yMWY2YjI5MzBmMjQifQ.eyJpYXQiOjE2ODUwODQ1MzAsImp0aSI6IjJlYzgyMjZmLThhNDAtNDBkMS05NjZlLTQ1M2Y1MGJhNzBmZiIsImlzcyI6Imh0dHBzOi8vMTAuMTM0LjU5LjIzNi5uaXAuaW8vYXV0aC9yZWFsbXMvdGVzdHNlcnZlciIsImF1ZCI6Imh0dHBzOi8vMTAuMTM0LjU5LjIzNi5uaXAuaW8vYXV0aC9yZWFsbXMvdGVzdHNlcnZlciIsInN1YiI6IjYyMDBhYmEyLTgwY2UtNGNiNS04MzI5LTBkYTQyNDYzZWJkMCIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJ0ZXN0c2VydmVyIiwic2Vzc2lvbl9zdGF0ZSI6ImYxMzNmOGY2LWRkODAtNDdkZi1hYWE1LWVjM2JiNTk3Njk2NSIsInNjb3BlIjoidGVzdHNlcnZlciBlbWFpbCBvZmZsaW5lX2FjY2VzcyBwcm9maWxlIiwic2lkIjoiZjEzM2Y4ZjYtZGQ4MC00N2RmLWFhYTUtZWMzYmI1OTc2OTY1In0.h4fow_FY-i32Cj_MWe3uHBFXL1e4dUcLFZoKdTt1keI
            teamspace: Initial Team Space
            project: Anshul_SVT
            branch: master
            assetId: 9a02ba2d-c5a9-4920-82ba-2dc5a959203a
