name: HCL OneTest Server

on: workflow_dispatch

jobs:
    OTS-Action:
        runs-on: self-hosted
        name: HCL OneTest Server
        steps:
         - name: Execute Test
           uses: HCL-TECH-SOFTWARE/onetest-server-action@main
           with:
            serverUrl: https://10.134.59.190.nip.io/
            offlineToken: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJkMWMyMDFiZC1mOWI4LTQ4OWYtYThmOS1kNmRjNGY4M2NjNzEifQ.eyJpYXQiOjE2NjYwOTc5ODQsImp0aSI6ImZjODg1NDc3LTJkYmYtNDJhMC1hZDcyLWI2YWNlNDg0ZjA0NiIsImlzcyI6Imh0dHBzOi8vMTAuMTM0LjU5LjE5MC5uaXAuaW8vYXV0aC9yZWFsbXMvdGVzdHNlcnZlciIsImF1ZCI6Imh0dHBzOi8vMTAuMTM0LjU5LjE5MC5uaXAuaW8vYXV0aC9yZWFsbXMvdGVzdHNlcnZlciIsInN1YiI6IjhmYjU2ZmI5LTFlYjctNDQ2Yi1iN2NlLWM4ZDA2NTMzNDcxZSIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJ0ZXN0c2VydmVyIiwic2Vzc2lvbl9zdGF0ZSI6IjgxZGMxMjU1LTkyNDItNDNhNy04MjJjLWM0NjcyZTNkZTMyMCIsInNjb3BlIjoidGVzdHNlcnZlciBlbWFpbCBvZmZsaW5lX2FjY2VzcyBwcm9maWxlIiwic2lkIjoiODFkYzEyNTUtOTI0Mi00M2E3LTgyMmMtYzQ2NzJlM2RlMzIwIn0.sax-3TElbpid2UolW0WRtvA0sZKd0pVluDuhEm9UR4s
            teamspace: Initial Team Space
            project: Anshul_SVT
            branch: master
            assetId: 71213726-2a9d-45d4-a137-262a9da5d436
