name: HCL OneTest Server

on: workflow_dispatch

jobs:
    OTS-Action:
        runs-on: self-hosted
        name: HCL OneTest Server
        steps:
         - name: Execute Test
           uses: HCL-TECH-SOFTWARE/onetest-server-action@main
           with:
            serverUrl: https://10.134.59.190.nip.io/
            offlineToken: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI4N2I0NzA3YS02NTFjLTRiOGUtOWY3Ni1lZDM2NGE2NjA4MGEifQ.eyJpYXQiOjE2NzcwNDg1MDksImp0aSI6Ijg4MjJiMWQzLTUwZGUtNGViYi1iNmNmLTJjNzVkM2M1YmM2MSIsImlzcyI6Imh0dHBzOi8vMTAuMTM0LjU5LjE5MC5uaXAuaW8vYXV0aC9yZWFsbXMvdGVzdHNlcnZlciIsImF1ZCI6Imh0dHBzOi8vMTAuMTM0LjU5LjE5MC5uaXAuaW8vYXV0aC9yZWFsbXMvdGVzdHNlcnZlciIsInN1YiI6IjYyZDZiYzBjLTQ3NWEtNDFhMy04MmE4LWVhNTIyZTRkY2FhMyIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJ0ZXN0c2VydmVyIiwic2Vzc2lvbl9zdGF0ZSI6IjI1MjYwZTAzLTNlNmMtNDFkOC04ZTExLWNmZjVlYTdkZDFkZSIsInNjb3BlIjoidGVzdHNlcnZlciBlbWFpbCBvZmZsaW5lX2FjY2VzcyBwcm9maWxlIiwic2lkIjoiMjUyNjBlMDMtM2U2Yy00MWQ4LThlMTEtY2ZmNWVhN2RkMWRlIn0.suE17l85OQ-nUcccVySOmymkrWMD-Jd5yBSbRnuTpl0
            teamspace: Initial Team Space
            project: Anshul_SVT
            branch: master
            assetId: 300be444-813a-4859-8be4-44813ab859eb
