name: HCL OneTest Server

on: workflow_dispatch

jobs:
    OTS-Action:
        runs-on: self-hosted
        name: HCL OneTest Server
        steps:
         - name: Execute Test
           uses: HCL-TECH-SOFTWARE/onetest-server-action@main
           with:
            serverUrl: https://master-hcl.tp-k8s.nonprod.hclpnp.com/
            offlineToken: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI2MmYxZjBjZC05N2QzLTQyM2UtOGUxMy0zYjY0MTI5M2MwZmEifQ.eyJpYXQiOjE2NjYxNzY2NTgsImp0aSI6ImIzMzYzMjZkLTJlODctNGJmMS05MzQwLWNiMTQ5NGFkMzE2OSIsImlzcyI6Imh0dHBzOi8vbWFzdGVyLWhjbC50cC1rOHMubm9ucHJvZC5oY2xwbnAuY29tL2F1dGgvcmVhbG1zL3Rlc3RzZXJ2ZXIiLCJhdWQiOiJodHRwczovL21hc3Rlci1oY2wudHAtazhzLm5vbnByb2QuaGNscG5wLmNvbS9hdXRoL3JlYWxtcy90ZXN0c2VydmVyIiwic3ViIjoiNDUyZThhOTEtMzhiMS00NTY4LTg5YjItYmUxYTAyZmFjMTcxIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6InRlc3RzZXJ2ZXIiLCJzZXNzaW9uX3N0YXRlIjoiZmFiZDIyNmMtMjRmMC00ZjQ2LWI1NzYtNzY0MWM1M2E5MTg1Iiwic2NvcGUiOiJ0ZXN0c2VydmVyIGVtYWlsIG9mZmxpbmVfYWNjZXNzIHByb2ZpbGUiLCJzaWQiOiJmYWJkMjI2Yy0yNGYwLTRmNDYtYjU3Ni03NjQxYzUzYTkxODUifQ.5ENUCLLy1f1kmZAjGE-GAAxVgiCC4XUNH2a3rW_y8sg
            teamspace: Initial Team Space
            project: Anshul_SVT
            branch: master
            assetId: 4527391d-b769-468c-a739-1db769368c5b
