name: HCL OneTest Server

on: workflow_dispatch

jobs:
    OTS-Action:
        runs-on: self-hosted
        name: HCL OneTest Server
        steps:
         - name: Execute Test
           uses: HCL-TECH-SOFTWARE/onetest-server-action@main
           with:
            serverUrl: https://10.134.59.190.nip.io/
            offlineToken: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJkMWMyMDFiZC1mOWI4LTQ4OWYtYThmOS1kNmRjNGY4M2NjNzEifQ.eyJpYXQiOjE2NjYwOTg0MjAsImp0aSI6ImNkNWM2ODE3LThiNTAtNDhjMy1hMTk1LTIyMjUwY2Q0Mzg0NiIsImlzcyI6Imh0dHBzOi8vMTAuMTM0LjU5LjE5MC5uaXAuaW8vYXV0aC9yZWFsbXMvdGVzdHNlcnZlciIsImF1ZCI6Imh0dHBzOi8vMTAuMTM0LjU5LjE5MC5uaXAuaW8vYXV0aC9yZWFsbXMvdGVzdHNlcnZlciIsInN1YiI6IjhmYjU2ZmI5LTFlYjctNDQ2Yi1iN2NlLWM4ZDA2NTMzNDcxZSIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJ0ZXN0c2VydmVyIiwic2Vzc2lvbl9zdGF0ZSI6IjdhZWIyYzE4LTM2N2UtNDg1Ni1iMGY3LWUwZDBjMzk2NmUwNiIsInNjb3BlIjoidGVzdHNlcnZlciBlbWFpbCBvZmZsaW5lX2FjY2VzcyBwcm9maWxlIiwic2lkIjoiN2FlYjJjMTgtMzY3ZS00ODU2LWIwZjctZTBkMGMzOTY2ZTA2In0.kTNfNVtMzV6iC7JmcrjzLiMk9BZIU_S_m7z1U5GCx0Y
            teamspace: Initial Team Space
            project: Anshul_SVT
            branch: master
            assetId: 9a346cc0-d7df-40a0-b46c-c0d7df90a002
